apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nextjs-ui-ingress
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
spec:
    ingressClassName: traefik
    tls:
        - hosts:
              - app.good-food.code-with-alex.com
          secretName: good-food-app-tls
    rules:
        - host: app.good-food.code-with-alex.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: nextjs-ui
                            port:
                                number: 3000
